name: AnyStatus

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nuget/setup-nuget@v1
    - uses: microsoft/setup-msbuild@v1.1
    - run: nuget restore src/AnyStatus.sln
    - run: msbuild src/AnyStatus.sln -t:rebuild -property:Configuration=Release -property:Platform=x64
